### ISSUE TITLE
Run fails to complete with --deploy-docker when submitted through slurm.

### ISSUE THREAD

**Issue by lowandrew** [phac-nml/snvphyl-galaxy-cli#1]
Hello,

I'm having issues when running on our cluster using the --deploy-docker option. The docker container appears to successfully deploy, and the run progresses up to a point, and then fails. Here's the log:

 Deploying Docker Container
==========================
Running 'docker run --cpus 4 --env SLURM_CPUS=4 --detach --publish 9934:80 --volume /mnt/nas/bio_requests/9934/fastqs:/snvphyl-data/fastq phacnml/snvphyl-galaxy-1.0.1:1.0.1b'
Docker id 83ecbc39b6d45d6fc6a3f49f27f2182a4a0ce101fec0df3e18b49d68eb48ca2d
Waiting for docker to complete launching Galaxy on port 9934 ......finished.  Galaxy in Docker has (hopefully) started successfully.
Took 0.60 minutes to deploy docker

Examining input fastq files
===========================
Structuring data in directory '/mnt/nas/bio_requests/9934/fastqs' like:
2015-SEQ-1145_S15_L001: paired {forward: /mnt/nas/bio_requests/9934/fastqs/2015-SEQ-1145_S15_L001_R1_001.fastq.gz, reverse: /mnt/nas/bio_requests/9934/fastqs/2015-SEQ-1145_S15_L001_R2_001.fastq.gz}
2017-BUR-0077_S5_L001: paired {forward: /mnt/nas/bio_requests/9934/fastqs/2017-BUR-0077_S5_L001_R1_001.fastq.gz, reverse: /mnt/nas/bio_requests/9934/fastqs/2017-BUR-0077_S5_L001_R2_001.fastq.gz}

Set up workflow input
=====================
setting parameter {irida.corefacility.ca/galaxy-shed/repos/nml/consolidate_vcfs/consolidate_vcfs/1.8.0, snv_abundance_ratio, 0.75}
setting parameter {irida.corefacility.ca/galaxy-shed/repos/nml/consolidate_vcfs/consolidate_vcfs/1.8.0, coverage, 5}
setting parameter {irida.corefacility.ca/galaxy-shed/repos/nml/verify_map/verify_map/1.8.0, mindepth, 5}
setting parameter {irida.corefacility.ca/galaxy-shed/repos/nml/consolidate_vcfs/consolidate_vcfs/1.8.0, mean_mapping, 30}
setting parameter {irida.corefacility.ca/galaxy-shed/repos/nml/find_repeats/findrepeat/1.8.0, length, 150}
setting parameter {irida.corefacility.ca/galaxy-shed/repos/nml/find_repeats/findrepeat/1.8.0, pid, 90}
setting parameter {irida.corefacility.ca/galaxy-shed/repos/nml/consolidate_vcfs/consolidate_vcfs/1.8.0, use_density_filter.threshold, 2}
setting parameter {irida.corefacility.ca/galaxy-shed/repos/nml/consolidate_vcfs/consolidate_vcfs/1.8.0, use_density_filter.window_size, 500}

Upload files to Galaxy
======================
Creating history in Galaxy name 'snvphyl-2017-BUR-0077-2017-09-26-run'
Uploading reference file /mnt/nas/bio_requests/9934/2017-BUR-0077.fasta
Uploading fastq files in history 'snvphyl-2017-BUR-0077-2017-09-26-run'
Uploading as link /mnt/nas/bio_requests/9934/fastqs/2017-BUR-0077_S5_L001_R1_001.fastq.gz
Uploading as link /mnt/nas/bio_requests/9934/fastqs/2015-SEQ-1145_S15_L001_R2_001.fastq.gz
Uploading as link /mnt/nas/bio_requests/9934/fastqs/2017-BUR-0077_S5_L001_R2_001.fastq.gz
Uploading as link /mnt/nas/bio_requests/9934/fastqs/2015-SEQ-1145_S15_L001_R1_001.fastq.gz
Waiting for library datasets to finish processing...4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.4.3.1.0.done
Building dataset collection named paired_datasets
Finished uploading data to history snvphyl-2017-BUR-0077-2017-09-26-run

Running workflow
================
Starting SNVPhyl version 1.0.1 type paired-end workflow in history snvphyl-2017-BUR-0077-2017-09-26-run
Workflow has started running in history snvphyl-2017-BUR-0077-2017-09-26-run on Galaxy http://localhost:9934 at 2017-09-26 09:44

Waiting for workflow completion 
===============================
percent complete (can initially decrease as more jobs are scheduled by Galaxy): 0...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...21...23...23...23...23...23...23...23...23...23...23...23...23...23...23...23...23...23...23...23...23...23...28...28...28...28...28...28...28...28...28...28...28...28...28...31...31...31...31...31...31...39...39...42...42...42...42...42...42...42...44...44...44...44...44...44...44...44...50...50...50...50...50...50...50...50...50...50...50...50...50...50...50...55...55...55...55...55...55...55...55...55...55...55...55...55...55...55...55...57...57...57...57...57...57...57...57...57...57...57...57...57...57...57...57...57...57...57...57...57...57...57...57...57...57...57...57...57...57...57...57...57...57...60...65...65...65...65...65...65...65...65...65...65...65...65...65...65...65...65...65...73...76...76...76...76...76...76...76...76...76...76...76...76...76...76...76...76...76...76...76...76...76...76...76...76...76...8683ecbc39b6d45d6fc6a3f49f27f2182a4a0ce101fec0df3e18b49d68eb48ca2d

Workflow finished at 2017-09-26 10:26

Getting workflow outputs
========================
Searching for dataset with name filterStats.txt
Searching for dataset with name mappingQuality.txt
Searching for dataset with name phylogeneticTree.newick
Searching for dataset with name snvAlignment.phy
Searching for dataset with name snvMatrix.tsv
Searching for dataset with name snvTable.tsv
Searching for dataset with name vcf2core.tsv
Getting provenance info from Galaxy

Finished
========
Took 42.92 minutes
Galaxy history f2db41e1fa331b3e on http://localhost:9934
Output in /mnt/nas/bio_requests/9934/output

Undeploying and cleaning up Docker Container
=============================================
Running 'docker rm -f -v 83ecbc39b6d45d6fc6a3f49f27f2182a4a0ce101fec0df3e18b49d68eb48ca2d'

The failure always seems to occur around the same point for this particular run - between 85 and 95 percent completion. The error log from slurm is completely empty, so I'm pretty mystified. 

Running on the same node with the exact same input files, port, and settings without going through slurm works perfectly. Any help would be greatly appreciated.

Thanks!

**Comment by apetkau** [comment]
Does the directory `/mnt/nas/bio_requests/9934/output` contain any files?  From the output you've posted, it looks like it completed successfully and generated all the output files (e.g., filterStats.txt, mappingQuality.txt, ...).  But, it may have have printed out the final 100% complete message.

**Comment by lowandrew** [comment]
For that job, the output files were generated and there. For other jobs with more input files, the process will tend to fail earlier on and output files won't be generated. (I've attached another log file for an instance where this happened.)
[job_249.txt](https://github.com/phac-nml/snvphyl-galaxy-cli/files/1334061/job_249.txt)

These larger jobs run to completion when run under identical conditions but not submitted via slurm.

Thanks again!

**Comment by apetkau** [comment]
Thanks for clarifying. Is there any files in the `output` directory even in the error case?  Depending on what went wrong, there may still be the files `dataset-provenance.json  history-provenance.json  run-settings.txt` in the output directory.  You can then search these files for additional error messages (e.g., `grep 'error' *.json`).

Since the jobs run to completion when not executed using slurm, my initial assumption is that slurm may be interfering or killing some of the jobs before they complete.  However, I'm at a bit of a loss as to how to figure out the exact cause.  I assume the slurm log files don't have much information do they?  How were you running this using slurm?

Running with lower CPUs could help out with this (less CPUs = less resources = less chance of being interfered with by slurm).  However, I noticed you've already tried out a variety of CPUs.  Another possibility is adjusting the maximum allowable memory, or some other resource available to docker (https://docs.docker.com/engine/admin/resource_constraints/).  I quickly added a command-line option to the **development** branch which should allow you to pass options directly to docker (e.g., `snvphyl.py ... --docker-other-options '--memory 4g'`).  You can also monitor the resources used by docker with the command `docker stats`.

Hopefully this gives you a few more options to diagnose the issue.  Sorry I don't have any specific answer for you right now.

**Comment by apetkau** [comment]
I am going to close this issue.  If you have more related questions please feel free to make another issue.
